#!/bin/bash

# Create user.toml under /hab/user space for package, do not overwrite if it exists
if [ ! -f /hab/user/{{ pkg.name }}/config/user.toml ]; then
  mkdir -p /hab/user/{{ pkg.name }}/config
  cp {{ pkg.path }}/default.toml /hab/user/{{ pkg.name }}/config/user.toml
fi