#######################################
# Chef Infra Client Configuration Settings
#######################################

# You don't usually need to change these.
# This project provides highly tuned defaults for you.
# If you don't have a strong reason for overriding these
# Then it's a good idea to remove them.

interval = 1800
# The number of seconds to wait between Chef Infra Client runs
# Default value: 1800

splay = 1800
# A random number of seconds between 0 and $splay to add AFTER the interval. Use this setting to avoid the thundering herd problem. Optimal to always set this equal to the interval, or else you may end up DDOSing your own internal resources.
# Default value: 1800

splay_first_run = 0
# A random number of seconds between 0 and $splay_first_run BEFORE the first Chef Infra Client runs, only on the first run. Used to avoid the thundering herd problem on new deployments. Optimal to always set to a function of your node count. Add 1 second for each node in your fleet. For example, if you have 1800 nodes, then you should set this value to 1800.
# Default value: 0

run_lock_timeout = 1800
# The number of seconds to lock the Chef Infra Client before allowing another run to begin.
# Default value: 1800

log_level = "warn"
# The level of logging to be stored in a log file for the Chef Infra Client.
# Possible levels: :auto (default), :debug, :info, :warn, :error, or :fatal.
# Default value: :warn (when a terminal is available) or :info (when a terminal is not available).

env_path_prefix = "/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
# The environment added to the path environment variable of the Chef Infra Client's run hook.
# Override this value if your Chef Infra Client needs access to a different path.
# Default value: /sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin

ssl_verify_mode = ":verify_peer"
# The verify mode for HTTPS requests.
# Use :verify_none for no validation of SSL certificates.
# Use :verify_peer for validation of all SSL certificates, including the Chef Infra Server connections, S3 connections, and any HTTPS remote_file resource URLs used in Chef Infra Client runs. This is the recommended setting.
# Depending on how OpenSSL is configured, the ssl_ca_path may need to be specified.
# Default value: :verify_peer.

# [automate]
# enable = false
# server_url = "https://<automate_url>/data-collector/v0/"
# token = "<automate_token>"

# The connection information for your Chef Automate server
# Setting enable = false will turn off this feature
# The server_url is the url to your Chef Automate Server
# The token is a token with the data_collector rights to the Chef Automate API
# Default value: false

#######################################
# End of Chef Infra Client Configuration Settings
#######################################


# The Chef License must be accepted to use this software: https://www.chef.io/end-user-license-agreement/
# Change [chef_license] from acceptance = "undefined" to acceptance = "accept-no-persist" or "accept" if you agree to the license.

[chef_license]
acceptance = "undefined"

#######################################
# Habitat On-Prem Builder Update settings
#######################################

[[opbldr]]

[opbldr.default]
# Source Habitat builder instance to obtain packages from and Personal Access Token to use
# Example: 
# source_builder = "https://bldr.habitat.sh"
source_builder = ""
source_PAT = ""

# Target Habitat builder instance where packages will be synchronized to and Personal Access Token to use
target_builder = ""
target_PAT = ""

# Filesystem location to use for downloading packages during sync process. Sub-folder hab_opbldr_update will be created to avoid undesired destruction with cleanup
# Example:
# tmp_dir = "/tmp/builder_sync"
tmp_dir = ""

# Origin to use for source and destination
origin = ""

# Optional - Channels to include with sync process.  If empty then default will be 'stable'
channels = []

# Optional - Packages names to include with sync process.  If empty, all pacakges on origin in selected channel(s) will be included.
# Example:
# packages = ["inspec", "chef-infra-client"]
packages = []

# Optional - Cleans up any downloaded files from tmp_dir after update process has completed
## valid options are enable or disable
cleanup = "disable"

# Additional jobs can be created by adding more opbldr sections.
#  Example:
# [opbldr.second]
# source_builder = ""
# source_PAT = ""
# target_builder = ""
# target_PAT = ""
# tmp_dir = ""
# origin = ""
# channels = []
# packages = []
# cleanup = ""

#######################################
# End Habitat On-Prem Builder Update settings
#######################################

