---
name: ci

on: [pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run Chef Delivery
      uses: actionshub/chef-delivery@master
      env:
        CHEF_LICENSE: accept-no-persist

  testing:
    needs: [delivery]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: PolicyFile test
        run: chef install policyfiles/Policyfile.rb
        env:
          CHEF_LICENSE: accept-no-persist
      - name: Install Chef Habitat
        uses: collinmcneese/chef-habitat-install@master
      - name: Build Habitat package
        run: source habitat plan.sh ; hab origin key generate ${pkg.origin} ; hab studio build .
        env:
          HAB_LICENSE: accept-no-persist
      # Reference repo, no direct tests to run
      # - name: kitchen
      #   run: kitchen converge
      #   env:
      #     CHEF_LICENSE: accept-no-persist
      #     KITCHEN_LOCAL_YAML: kitchen.shell.yml

